### ISSUE TITLE
Few errors

### ISSUE THREAD

**Issue by dovahkrid** [marcomusy/pianoplayer#14]
- First is 

`music21: Certain music21 functions might need these optional packages: matplotlib, numpy, scipy;
if you run into errors, install them by following the instructions at http://mit.edu/music21/doc/installing/installAdditional.html`

`Music21 v.4 is the last version that will support Python 2. Please start using Python 3 instead.`

`Set music21.environment.UserSettings()['warnings'] = 0
to disable this message.`

I'm using Python 3.7

- Second is

`sh: musescore: command not found`

I'm using Musescore 3. 

- And when I open the output.xml, it doesn't seem to work.

https://imgur.com/17DG3JQ

Here is the sheet I used: https://musescore.com/user/13934766/scores/3579721

**Comment by marcomusy** [comment]
Hi, thanks for reporting this..

> * First is
> 
> `music21: Certain music21 functions might need these optional packages: matplotlib, numpy, scipy; if you run into errors, install them by following the instructions at http://mit.edu/music21/doc/installing/installAdditional.html`
> 
> `Music21 v.4 is the last version that will support Python 2. Please start using Python 3 instead.`
> 
> `Set music21.environment.UserSettings()['warnings'] = 0 to disable this message.`
> 
> I'm using Python 3.7

I think you can ignore all this, but i will set the user settings to 0 in the code.
 
> * Second is
> 
> `sh: musescore: command not found`
> 
> I'm using Musescore 3.

this only works in linux systems where `musescore` must be in your PATH.

> * And when I open the output.xml, it doesn't seem to work.
> 
> https://imgur.com/17DG3JQ
> 
> Here is the sheet I used: https://musescore.com/user/13934766/scores/3579721

The weird stuff that shows up at the start in the snapshot is due to some corruption of the musescore file and/or inability of music21 to convert to xml, but it is not due to `pianoplayer`, the rest looks normal.. try to download the original as xml format and use that..

**Comment by dovahkrid** [comment]
GUI doesn't support mxl (which Musescore web only has that, not xml), I have to use command to open it.

But it works, not perfect (break page, lose arpeggios, mix up clefs) but good enough. Thank you
