### ISSUE TITLE
Errors package

### ISSUE THREAD

**Issue by AmitMY** [marcomusy/pianoplayer#22]
I downloaded the 2000 most popular piano sheet music from Musescore, as mxl.

I ran the lastest pip version of `pianoplayer` on all of the files (on `XXS` setting), and started getting errors, like https://github.com/marcomusy/pianoplayer/issues/21 and others (python errors).

Here I share an archive of all of the files that had execution errors (148 out of 2000), in the hope this helps you make this system more robust.

File names are constructed from musescore ID, and title, so you can always trace back to musescore.com in order to see the file.

[errors.zip](https://github.com/marcomusy/pianoplayer/files/4456001/errors.zip)

**Comment by marcomusy** [comment]
Thanks Amit for this nice contribution, I hope I'll be able to dedicate some time to fix these issues!

**Comment by marcomusy** [comment]
Thanks again for your contribution and sorry for the late reply.
These should be fixed in the latest release for  `pianoplayer`, some of the music-xml in the list might be corrupted other cause crashing in `music21` - I posted an issue in music21:
https://github.com/cuthbertLab/music21/issues/786#issuecomment-765667562
but they don't seem to care.. :(

**Comment by jacobtylerwalls** [comment]
Hi all, I'm one of the contributors to music21. We care about the package, however, we also appreciate reporters providing steps to reproduce, or in the case of parsing errors, providing small reproducing examples instead of entire files. That said, from your post I was able to spot some improvements we can make to music21: one bugfix and one error we can raise closer to the source to be more informative.

That said, if your app programmatically imports MusicXML, it's import to wrap the parsing in a `try` block. The music21 MusicXML parser won't silence parsing errors -- it's up to the consuming program to decide how loudly to fail. Several of the files in the ticket are invalid MusicXML that even Finale won't open.

`music21.exceptions21.Music21Exception` is a class of exception you should ideally be catching. All best, Jacob

**Comment by marcomusy** [comment]
> Hi all, I'm one of the contributors to music21. We care about the package, however, we also appreciate reporters providing steps to reproduce, or in the case of parsing errors, providing small reproducing examples instead of entire files. 

No. Sorry - that's _exactly_ what I did: to post a python script to reproduce the observed behavior. 
You are the maintainer, it's your job to find out what happens in _your_ package.  It's just rude to close the issue the way you did.

> That said, from your post I was able to spot some improvements we can make to music21: one bugfix and one error we can raise closer to the source to be more informative.

I'm happy about that, and thanks for getting back on this and for the nice software you created.
Regards
Marco
