### ISSUE TITLE
Is there a description of the algorithm in a document/publication?

### ISSUE THREAD

**Issue by Alia-morsi** [marcomusy/pianoplayer#23]
I might use pianoplayer in one of the intermediary steps in my master thesis. So, I was wondering whether its methodology is documented somewhere so I can give a proper description of the logic behind it, and also to properly cite it :)

Thanks!

**Comment by marcomusy** [comment]
Dear Alia
Thanks for the interest in the software, you can cite it as:

M. Musy, "`pianoplayer`, an automatic fingering generator for piano scores" (Version 2.1.0). Zenodo. http://doi.org/10.5281/zenodo.3376237. 2019, August 23.

The superficial algorithm description is given in readme:

>The algorithm minimizes the fingers speed needed to play a sequence of notes or chords by searching through feasible combinations of fingerings.
One possible advantage of this algorithm over similar ones is that it is completely dynamic, which means that it takes into account the physical position and speed of fingers while moving on the keyboard and the duration of each played note. It is not based on a static look-up table of likely or unlikely combinations of fingerings.

So the algorithm basically loops over feasible combinations of finger sequences and finds the one that. at any given point in time, minimizes the average speed of the sequence of the future notes still to be played. 
The length (search depth) of this sequence can be specified.
Such greedy search is possible because there's a number of combinations that can be ruled out from start (e.g. the 3rd finger crossing the 4th on a fast note).
Chords are dealt with by splitting the chord into a normal ascending rapid sequence of notes.

The algorithm in spite of its simplicity (the core of the python code is only 250 lines) can often yield surprisingly good fingering combinations, and to be fair sometime some very bad result too! :)

I hope I'll find soon some spare time to improve on some aspects and update the graphics rendering.
